# Generated by Django 3.1.4 on 2020-12-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.userprofile'),
            preserve_default=False,
        ),
    ]
