# Generated by Django 3.1.4 on 2020-12-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
